services:
  - type: web
    name: tif3-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.enableCORS false"
    envVars:
      - key: DB_HOST
        value: uvabase
      - key: DB_NAME
        value: uva_db
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: admin
      - key: DB_PORT
        value: 5432
